using System ;
using System.Collections.Generic ;
using System.Linq ;
using System.Threading.Tasks ;
using UnityEngine ;

//<auto-generated>
//Beast.ShareClientGeneratorによる自動生成されたファイルです。手動変更禁止
//<auto-generated>
namespace Template
{
    public partial class PlayerData
    {
        /// <summary>
        /// PlayerData 更新用クラス
        /// </summary>
        [Serializable]
        public partial class Updater
		{
			/// <summary>
			/// 識別子群
			/// </summary>
            public List<long> Ids { get { return ids ; } }
            [SerializeField]
            public List<long> ids ;
        }

		//-------------------------------------------------------------------------------------------

		/// <summary>
		/// 識別子群
		/// </summary>
		public static List<long>	Ids { get ; private set ; }

		/// <summary>
		/// 更新
		/// </summary>
		/// <param name="updater"></param>
		/// <returns></returns>
		public static bool Update( Updater updater )
		{
			bool isUpdated = false ;
			if( updater.Ids != null )
			{
				Ids = updater.Ids ;
				isUpdated = true ;
			}

			return isUpdated ;
		}

		/// <summary>
		/// プレイヤーデータをクリアする
		/// </summary>
		public static void Clear()
		{
			Ids = null ;
		}
	}
}
