using System ;
using System.Collections.Generic ;
using System.Collections ;
using System.Linq ;
using UnityEngine ;

//<auto-generated>
//Beast.ShareClientGeneratorによる自動生成されたファイルです。手動変更禁止
//<auto-generated>
namespace Template
{
	/// <summary>
	/// サーバーによって生成されたコード
	/// </summary>
	public partial class PlayerDataManager
	{
		//---------------------------------------------------------------------------
#if UNITY_EDITOR
		// 各プレイヤーデータの UnityEditor の Inspector でのモニタリング用の定義
		[SerializeField]
		protected List<long> Ids ;

		/// <summary>
		/// 各マスターデータを UnityEditor の Inspector に表示する設定を行う
		/// </summary>
		public void SetMonitor()
		{
			this.Ids = PlayerData.Ids ;
		}
#endif
	}
}
