using System ;
using System.Collections.Generic ;
using System.Linq ;
using System.Text ;
using System.Threading.Tasks ;

using UnityEngine ;

using Template.Enumerator ;

//<auto-generated>
//Beast.ShareClientGeneratorによる自動生成されたファイルです。手動変更禁止
//<auto-generated>
namespace Template.WebAPIs
{
	[Serializable]
	public partial class RequestBase
	{
		/// <summary>
		/// システムバージョン
		/// </summary>
		public String SystemVersion { get { return systemVersion ; } set { systemVersion = value ; } }
		[SerializeField]
		public String systemVersion ;

		/// <summary>
		/// マスターデータバージョン
		/// </summary>
		public Int64 MasterDataVersion { get { return masterDataVersion ; } set { masterDataVersion = value ; } }
		[SerializeField]
		public Int64 masterDataVersion ;

		/// <summary>
		/// プラットフォームコード
		/// </summary>
		public PlatformCodes PlatformCode { get { return platformCode ; } set { platformCode = value ; } }
		[SerializeField]
		public PlatformCodes platformCode ;

		/// <summary>
		/// デバイス名
		/// </summary>
		public String DeviceName { get { return deviceName ; } set { deviceName = value ; } }
		[SerializeField]
		public String deviceName ;

		/// <summary>
		/// アクセストークン
		/// </summary>
		public String AccessToken { get { return accessToken ; } set { accessToken = value ; } }
		[SerializeField]
		public String accessToken ;
	}
}
